/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbcpg.ireport.demo1;


/**
 *
 * @author Admin01
 */
public class ReportDemo extends javax.swing.JFrame {

    /**
     * Creates new form ReportDemo
     */
    public ReportDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jspReport = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("show report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 862, Short.MAX_VALUE))
                    .addComponent(jspReport))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspReport, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        //custom initialization
        PG.url = "jdbc:postgresql://localhost:5432/todos";
        PG.username = "postgres";
        PG.password = "postgres";
        PG.className = "org.postgresql.Driver";
        
        try{
            if(PG.openDB()){
                String reportName = "src\\com\\jdbcpg\\ireport\\demo1\\report1.jrxml";
                UIC.Report.viewReport(reportName);
                //UIC.Report.viewReport(jspReport, reportName);
                PG.closeDB();
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /** iReport code snippets */
    /*
    String reportPath = "C:\\reports\\report1.jasper";
    JasperReport jr = JasperCompileManager.compileReport(reportPath);
    JasperPrint jp = JasperFillManager.fillReport(jr, null, PG.conn);
    JasperViewer.viewReport(jp);                    
    */

    /*
    String sourceName = "C:\\reports\\report-todos.jrxml";
    JasperReport report = JasperCompileManager.compileReport(sourceName);
    JasperPrint filledReport = JasperFillManager.fillReport(report, null, PG.conn);                
    this.getContentPane().add(new JRViewer(filledReport));
    this.pack();
    */

    /*
    JasperDesign jasperDesign = JRXmlLoader.load("C:\\reports\\report-todos.jrxml");
    String sql = "select *,\n" +
        "(select count(*) from task where isDone='YES') as tYes,\n" +
        "(select count(*) from task where isDone='NO') as tNo\n" +
        "from  task";
    JRDesignQuery newQuery = new JRDesignQuery();
    newQuery.setText(sql);
    jasperDesign.setQuery(newQuery);
    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, PG.conn);
    JasperViewer.viewReport(jasperPrint);
    */

    /*
    //Working - Display static report outside the frame
    JasperDesign jasperDesign = JRXmlLoader.load("C:\\reports\\report-todos.jrxml");
    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, PG.conn);
    JasperViewer.viewReport(jasperPrint);                
    */

    /*
    //Working - Display dynamic report inside the frame
    String path1 = "C:\\reports\\report-todos.jrxml";
    String path2 = "src/com/jdbcpg/ireport/demo1/report1.jrxml";
    JasperDesign jasperDesign = JRXmlLoader.load(path2);
    JasperReport jReport = JasperCompileManager.compileReport(jasperDesign);
    JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, PG.conn);
    JRViewer viewer = new JRViewer(jPrint);
    viewer.setOpaque(true);
    viewer.setVisible(true);
    jspReport.add(viewer);
    jspReport.setViewportView(viewer);
    */

    //Working - Display dynamic report inside the frame  
    /*

    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jspReport;
    // End of variables declaration//GEN-END:variables
}
